[package]
name = "otelo-query"
description = "Parses and completes the query language that filters otelo's logs, spans, and metrics"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
serde = { workspace = true }
utoipa = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[lints]
workspace = true
